# Generated by Django 5.2.7 on 2025-10-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationmodel', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='usertype',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
